pull_request_rules:
  - name: automatic merge for Dependabot pull requests
    conditions:
      - author~=^dependabot(|-preview)\[bot\]$
      - "status-success=welcome"
      - "status-success=netlify/condescending-wescoff-06a3b4/deploy-preview"
    actions:
      merge:
        method: merge
  - name: automatic merge for ImgBot pull requests
    conditions:
      - author=imgbot[bot]
      - "status-success=welcome"
      - "status-success=netlify/condescending-wescoff-06a3b4/deploy-preview"
    actions:
      merge:
        method: merge
  - name: automatic merge for Snyk bot pull requests
    conditions:
      - author=snyk-bot[bot]
      - "status-success=welcome"
      - "status-success=netlify/condescending-wescoff-06a3b4/deploy-preview"
    actions:
      merge:
        method: merge
  - name: automatic merge for restyled bot pull requests
    conditions:
      - author=restyled-io[bot]
    actions:
      merge:
        method: merge
  - name: automatic merge Zalbani pull requests
    conditions:
      - author=Zalbani
      - "status-success=welcome"
      - "status-success=netlify/condescending-wescoff-06a3b4/deploy-preview"
      - "status-success=WIP"
    actions:
      merge:
        method: merge
  - name: Automatic merge ⬇️ on approval ✔
    conditions:
      - "#approved-reviews-by>=1"
      - "status-success=welcome"
      - "status-success=netlify/condescending-wescoff-06a3b4/deploy-preview"
      - "status-success=WIP"
    actions:
      merge:
        method: merge
